blog/urls.py
from django.urls import path

from blog.views.comment import CommentCreate
from blog.views.home import home
from blog.views.post import PostView, PostCreate, PostUpdate, PostDelete,PostSearch

app_name = 'blog'
urlpatterns = [
    # ex: /blog/
    path('', home, name='home'),
    # ex: /blog/dusan
    path('<str:username>', home, name='user_posts'),
    # ex: /blog/post/5/
    path('post/<int:pk>/', PostView.as_view(), name='post'),
    # ex: /blog/post/create/
    path('post/create/', PostCreate.as_view(), name='create_post'),
    # ex: /blog/post/5/update/
    path('post/create/<int:pk>/update', PostUpdate.as_view(), name='update_post'),
    # ex: /blog/post/5/delete/
    path('post/<int:pk>/delete/', PostDelete.as_view(), name='delete_post'),
    # ex: /blog/post/5/comment/
    path('post/<int:pk>/comment/', CommentCreate.as_view(), name='create_comment'),
    path('post/search', PostSearch.as_view(), name='search_post'),
    # path('/', home, name='home_search'),
]

mysite/urls.py
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import path, include

from blog.views.register import RegisterView

urlpatterns = [
    path('blog/', include('blog.urls')),
    path('admin/', admin.site.urls),
    path('login/', auth_views.LoginView.as_view(template_name='blog/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(next_page='blog:home')),
    path('register/', RegisterView.as_view(), name='register'),
    path('', include('django.contrib.auth.urls'))
]

blog/models/comment.py
from django.contrib.auth.models import User
from django.db import models

from blog.models.post import Post


class Comment(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    body = models.TextField()
    pub_date = models.DateTimeField('date published', auto_now_add=True)

    def __str__(self):
        return '"{body}..." on {post_title} by {username}'.format(body=self.body[:20],
                                                                  post_title=self.post.title,
                                                                  username=self.user.username)

blog/models/post.py
from django.contrib.auth.models import User
from django.db import models
from django.urls import reverse

class Tag(models.Model):
    name = models.CharField(max_length=100)


class Post(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    title = models.CharField(max_length=80)
    body = models.TextField()
    tag = models.ManyToManyField(Tag)
    pub_date = models.DateTimeField('date published', auto_now_add=True)

    def get_absolute_url(self):
        return reverse('blog:post', kwargs={'pk': self.pk})

    def __str__(self):
        return '"{title}" by {username}'.format(title=self.title,
                                                username=self.user.username)

blog/views/comment.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse, reverse_lazy
from django.views.generic import CreateView

from blog.models.comment import Comment
from blog.models.post import Post


class CommentCreate(LoginRequiredMixin, CreateView):
    model = Comment
    fields = ['body']
    template_name = 'blog/create_comment.html'
    login_url = reverse_lazy('login')

    def form_valid(self, form):
        form.instance.user = self.request.user
        form.instance.post = Post.objects.get(id=self.kwargs['pk'])
        return super().form_valid(form)

    def get_success_url(self):
        return reverse('blog:post', kwargs={'pk': self.kwargs['pk']})

blog/views/home.py
from django.contrib.auth.models import User
from django.core.paginator import Paginator
from django.shortcuts import render

from blog.models.post import Post,Tag

NUM_OF_POSTS = 5


def home(request, username=None):
    first_name = ''
    last_name = ''
    if username:
        user = User.objects.get(username=username)
        first_name = user.first_name
        last_name = user.last_name
        # post_list = Post.objects.filter(user=user)
        username = "tag1"
        b1 = Tag.objects.get(name = username)
        posts = Post.objects.filter(tag=b1)
    else:
        # post_list = Post.objects.all()
        posts = Post.objects.filter()

    # post_list = post_list.order_by('-pub_date')

    # paginator = Paginator(post_list, NUM_OF_POSTS)  # Show NUM_OF_PAGES posts per page
    # page = request.GET.get('page')

    # posts = paginator.get_page(page)

    return render(request, 'blog/home.html', {'posts': posts,
                                              'first_name': first_name,
                                              'last_name': last_name,
                                              'home_page':True,})

blog/views/post.py
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.urls import reverse_lazy
from django.views import generic
from django.views.generic import CreateView, UpdateView, DeleteView, ListView

from blog.models.comment import Comment
from blog.models.post import Post,Tag
from django.shortcuts import render

from django import forms

class NameForm(forms.Form):
    tags = forms.CharField(label='Your name', max_length=100)

# def PageObjects(request):
#     print(request)
#   if request.method == 'POST':
#     form = NameForm(request.POST)
#     print(form)

#     if form.is_valid():
#       answer = form.cleaned_data['value']

class PostView(generic.DetailView):
    model = Post
    template_name = 'blog/post.html'

    def get_context_data(self, **kwargs):
        # Call the base implementation first to get a context
        context = super().get_context_data(**kwargs)
        # Add in the username
        comments = Comment.objects.filter(post=self.kwargs['pk'])
        post = Post.objects.filter(pk = self.kwargs['pk'])
        context['comments'] = comments
        #post=self.kwargs['tag']
        for item in post:
            # tagObj = item.object
            print(item.tag.name)
        # print(post[0]['user'])
        # context['tag'] = post.name
        return context


class PostCreate(LoginRequiredMixin, CreateView):
    model = Post
    fields = ['title', 'body']
    template_name = 'blog/create_post.html'
    login_url = reverse_lazy('login')

    def form_valid(self, form):
        form.instance.user = self.request.user
        return super().form_valid(form)

class PostSearch(LoginRequiredMixin, CreateView):
    model = Post
    fields = ['tag']
    allTags = Tag.objects.filter()
    names = []
    for tag in allTags:
        my_tuple = (tag.name,tag.name)
        names.append(tag)
    # form = NameForm()
    # return render(request, '/blog/search_post.html', {'form': form})
    template_name = 'blog/search_post.html'
    login_url = reverse_lazy('login')

    # def test_func(self):
    #     return Post.objects.get(id=self.kwargs['pk']).user == self.request.user


class PostUpdate(LoginRequiredMixin, UserPassesTestMixin, UpdateView):
    model = Post
    fields = ['title', 'body']
    template_name = 'blog/create_post.html'
    login_url = reverse_lazy('login')

    def test_func(self):
        return Post.objects.get(id=self.kwargs['pk']).user == self.request.user


class PostDelete(LoginRequiredMixin, UserPassesTestMixin, DeleteView):
    model = Post
    success_url = reverse_lazy('blog:home')
    login_url = reverse_lazy('login')

    def test_func(self):
        return Post.objects.get(id=self.kwargs['pk']).user == self.request.user

blog/views/register.py
from django.contrib.auth.hashers import make_password
from django.contrib.auth.models import User
from django.urls import reverse_lazy
from django.views.generic import CreateView


class RegisterView(CreateView):
    model = User
    fields = ['username', 'password', 'first_name', 'last_name', 'email']
    template_name = 'blog/registration.html'
    success_url = reverse_lazy('login')

    def form_valid(self, form):
        # Hash password before sending it to super
        form.instance.password = make_password(form.instance.password)
        return super().form_valid(form)

blog/templates/blog/base.html
<!-- this is base template with navbar and footer -->
{% load static %}

<!doctype html>
<html class="no-js" lang="en">

<head>
    <meta charset="utf-8">
    
    <!--====== Title ======-->
    <title>Reflections</title>
    
    <meta name="description" content="">

    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!--====== Favicon Icon ======-->
    <link rel="shortcut icon" href="{% static 'assets/images/favicon.png' %}" type="image/png">
        
    <!--====== Magnific Popup CSS ======-->
    <link rel="stylesheet" href="{% static 'assets/css/magnific-popup.css' %}">
        
    <!--====== Slick CSS ======-->
    <link rel="stylesheet" href="{% static 'assets/css/slick.css' %}">
        
    <!--====== Line Icons CSS ======-->
    <link rel="stylesheet" href="{% static 'assets/css/LineIcons.css' %}">
        
    <!--====== Bootstrap CSS ======-->
    <link rel="stylesheet" href="{% static 'assets/css/bootstrap.min.css' %}">
    
    <!--====== Default CSS ======-->
    <link rel="stylesheet" href="{% static 'assets/css/default.css' %}">
    
    <!--====== Style CSS ======-->
    <link rel="stylesheet" href="{% static 'assets/css/style.css' %}">

    <link rel="stylesheet" href="{% static 'assets/css/icon-font.css' %}">

    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">

    <link href="https://fonts.googleapis.com/css?family=Montserrat:300,400,500,600" rel="stylesheet">

    <link rel="stylesheet" href="{% static 'assets/css/login_style.css' %}">

    
</head>

<body>
    <!--[if IE]>
    <p class="browserupgrade">You are using an <strong>outdated</strong> browser. Please <a href="https://browsehappy.com/">upgrade your browser</a> to improve your experience and security.</p>
  <![endif]-->
   
    <!--====== PRELOADER PART START ======-->

    <!-- <div class="preloader">
        <div class="loader">
            <div class="ytp-spinner">
                <div class="ytp-spinner-container">
                    <div class="ytp-spinner-rotator">
                        <div class="ytp-spinner-left">
                            <div class="ytp-spinner-circle"></div>
                        </div>
                        <div class="ytp-spinner-right">
                            <div class="ytp-spinner-circle"></div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div> -->

    <!--====== PRELOADER PART ENDS ======-->
    
    <!--====== NAVBAR TWO PART START ======-->
    {%if home_page %}
    <section class="navbar-area">
    {% else %}
    <section class="navbar-area sticky">
    {% endif %}
        <div class="container">
            <div class="row">
                <div class="col-lg-12">
                    <nav class="navbar navbar-expand-lg">
                       
                        <a class="navbar-brand" href="{% url 'blog:home' %}">
                            <img src="{% static 'assets/images/logo.svg' %}" alt="Logo">
                        </a>
                        
                        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarTwo" aria-controls="navbarTwo" aria-expanded="false" aria-label="Toggle navigation">
                            <span class="toggler-icon"></span>
                            <span class="toggler-icon"></span>
                            <span class="toggler-icon"></span>
                        </button>

                        <div class="collapse navbar-collapse sub-menu-bar" id="navbarTwo">
                            <ul class="navbar-nav ml-auto">
                                <li class="nav-item active"><a class="page-scroll" href="{% url 'blog:home' %}">home</a></li>
                                <li class="nav-item"><a class="page-scroll" href="{% url 'blog:home' %}#blogs">Blogs</a></li>
                                {% if user.is_authenticated %}
                                    <li class="nav-item"><a class="page-scroll" href="{% url 'blog:create_post' %}">publish</a></li>
                                {% else %}
                                    <li class="nav-item"><a class="page-scroll" href="{% url 'login' %}">publish</a></li>
                                {% endif %}
                                <li class="nav-item"><a class="page-scroll" href="{% url 'blog:search_post'%}">search</a></li>
                            </ul>
                        </div>
                        
                        <div class="navbar-btn  d-sm-inline-block ml-20">
                            <ul>
                                {% if not user.is_authenticated %}
                                    <li><a class="solid" href="{% url 'login' %}">Login</a></li>
                                {% else %}
                                    <li><a class="solid" href="{% url 'logout' %}">logout</a></li>
                                {% endif %}
                            </ul>
                        </div>
                    </nav> <!-- navbar -->
                </div>
            </div> <!-- row -->
        </div> <!-- container -->
    </section>

    <!--====== SLIDER PART START ======-->

    {%if home_page %}
    <div id="content">
    {% else %}
    <div id="content" class="mt-200">
    {% endif %}
        {% block content %}{% endblock %}
    </div>

    <hr>

    <!--====== FOOTER PART START ======-->

    <section class="footer-area footer-dark">
        <div class="container">
            <div class="row justify-content-center">
                <div class="col-lg-6">
                    <div class="footer-logo text-center">
                        <a class="mt-30" href="index.html"><img src="{% static 'assets/images/logo.svg' %}" alt="Logo"></a>
                    </div> <!-- footer logo -->
                    <div class="copyright text-center mt-35">
                        <div class="col-sm-12">
                            {% if user.is_authenticated %}
                                <p class="text"> Currently logged in as {{ user.username }}</p>
                            {% endif %}
                        </div>
                        <p class="text">This site is developed as a part of course work for DDS at BITS Pilani </a> </p>
                    </div> <!--  copyright -->
                    <div class="footer-support text-center">
                        
                        <span class="number">Developed by</span>
                        <span class="mail">Mohammed Ajaaz - 2019H1030019H</span>
                        <span class="mail">Anupam Chandra - 2019H1030020H</span>
                    </div>
                </div>
            </div> <!-- row -->
        </div> <!-- container -->
    </section>

    <!--====== FOOTER PART ENDS ======-->
    
    <!--====== BACK TOP TOP PART START ======-->

    <a href="#" class="back-to-top"><i class="lni lni-chevron-up"></i></a>

    <!--====== BACK TOP TOP PART ENDS ======-->    

    <!--====== PART START ======-->

<!--
    <section class="">
        <div class="container">
            <div class="row">
                <div class="col-lg-">
                    
                </div>
            </div>
        </div>
    </section>
-->

    <!--====== PART ENDS ======-->




    <!--====== Jquery js ======-->
    <script src="{% static 'assets/js/vendor/jquery-1.12.4.min.js' %}"></script>
    <script src="{% static 'assets/js/vendor/modernizr-3.7.1.min.js' %}"></script>
    
    <!--====== Bootstrap js ======-->
    <script src="{% static 'assets/js/popper.min.js' %}"></script>
    <script src="{% static 'assets/js/bootstrap.min.js' %}"></script>
    
    <!--====== Slick js ======-->
    <script src="{% static 'assets/js/slick.min.js' %}"></script>
    
    <!--====== Magnific Popup js ======-->
    <script src="{% static 'assets/js/jquery.magnific-popup.min.js' %}"></script>
    
    <!--====== Ajax Contact js ======-->
    <script src="{% static 'assets/js/ajax-contact.js' %}"></script>
    
    <!--====== Isotope js ======-->
    <script src="{% static 'assets/js/imagesloaded.pkgd.min.js' %}"></script>
    <script src="{% static 'assets/js/isotope.pkgd.min.js' %}"></script>
    
    <!--====== Scrolling Nav js ======-->
    <script src="{% static 'assets/js/jquery.easing.min.js' %}"></script>
    <script src="{% static 'assets/js/scrolling-nav.js' %}"></script>
    
    <!--====== Main js ======-->
    <script src="{% static 'assets/js/main.js' %}"></script>
    
</body>

</html>

blog/templates/blog/create_comment.html
{% extends "blog/base.html" %}

{% block content %}
    <div class="container ">
        <div class="row ">
            <div class="col-md-6 col-md-offset-3">

                <!-- Form - Blog Comment -->
                <form action="" method="post" class="form-horizontal">

                    {% csrf_token %}

                    <div class="form-group">
                        <div class="col-sm-9">

                            <!-- Errors - body -->
                            {% if form.body.errors %}
                                <label class="alert alert-danger">{{ form.body.errors }}</label>
                            {% endif %}
                            <h4 class="mb-10">Enter the comment</h4>
                            <!-- Form field - body -->
                            <textarea placeholder="Body"
                                      class="form-control"
                                      name="body" rows="6" cols="60" style="width: auto;"
                                      required ></textarea>

                        </div>
                    </div>

                    <div class="form-group">
                        <div class="col-sm-5">

                             <!-- Submit button -->
                            <button type="submit" class="btn btn-primary btn-block solid mt-20">Save</button>

                        </div>
                    </div>

                </form>

            </div>
        </div>
    </div>
{% endblock content %}

blog/templates/blog/create_post.html
{% extends "blog/base.html" %}

{% block content %}
    <div class="container " style="height: 50vh; ">
        <div class="row justify-content-center ">
            <div class="col-md-9 col-md-offset-3">

                <!-- Form - Blog Post -->
                <form action="" method="post" class="form-horizontal">

                    {% csrf_token %}

                    <div class="form-group">
                        <div class="col-sm-9">

                            <!-- Errors - title -->
                            {% if form.title.errors %}
                                <label class="alert alert-danger">{{ form.title.errors }}</label>
                            {% endif %}

                            <!-- Form field - title -->
                            <h3 class="mb-10">Enter Title:</h3>
                            <input type="text"
                                   placeholder="Title"
                                   class="form-control"
                                   name="title"
                                   value="{{ form.title.value|default:"" }}">

                        </div>
                    </div>

                    <div class="form-group mt-20 ">
                        <div class="col-sm-9">

                            <!-- Errors - body -->
                            {% if form.body.errors %}
                                <label class="alert alert-danger">{{ form.body.errors }}</label>
                            {% endif %}

                            <!-- Form fields - body -->
                            <h3 class="mb-10">Enter Blog:</h3>
                            <textarea placeholder="Body"
                                      class="form-control h-50"
                                      name="body">{{ form.body.value|default:"" }}</textarea>

                        </div>
                    </div>

                    <div class="form-group mt-20">
                        <div class="col-sm-9">

                            <!-- Submit button -->
                            <button type="submit" class="btn btn-primary btn-block">Save</button>

                        </div>
                    </div>

                </form>

            </div>
        </div>
    </div>
{% endblock content %}

blog/templates/blog/home.html
{% extends "blog/base.html" %}
{% load static %}

{% block content %}

    <section id="home" class="slider_area">
            <div id="carouselThree" class="carousel slide" data-ride="carousel">
                <div class="carousel-inner">
                    <div class="carousel-item active">
                        <div class="container">
                            <div class="row">
                                <div class="col-lg-6">
                                    <div class="slider-content">
                                        <h1 class="title">Reflections.</h1>
                                        <p class="text">Hi, this is my personal blogging website where we discuss computer science, finance and life in general</p>
                                        <ul class="slider-btn rounded-buttons">
                                            <li><a class="main-btn rounded-one" href="{% url 'blog:create_post' %}">publish a blog</a></li>
                                            <!-- <li><a class="main-btn rounded-two" href="#">DOWNLOAD</a></li> -->
                                        </ul>
                                    </div>
                                </div>
                            </div> <!-- row -->
                        </div> <!-- container -->
                        <div class="slider-image-box d-none d-lg-flex align-items-end">
                            <div class="slider-image">
                                <img src="{% static 'assets/images/slider/1.png' %}" alt="Hero">
                            </div> <!-- slider-imgae -->
                        </div> <!-- slider-imgae box -->
                    </div> <!-- carousel-item -->
            </div>
        </section>


        <section id="blogs" class="features-area">
            <div class="container">
                
                <div class="row justify-content-center">
                    <div class="col-lg-6 col-md-10">
                        <div class="section-title text-center pb-10">
                            <h3 class="title">Recently Published</h3>
                            <p class="text">Checkcout some of my most blog posts and share your opinions and thoughts</p>
                        </div> <!-- row -->
                    </div>
                </div> <!-- row -->
                <div class="row justify-content-center">
                    {% for post in posts %}

                    <div class="col-lg-6 col-md-7 col-sm-9">
                        <div class="single-features mt-40">
                            <div class="features-title-icon d-flex justify-content-between">
                                <h4 class="features-title"><a href="{% url 'blog:post' post.pk %}">{{ post.title }}</a></h4>
                            </div>
                            <div class="features-content">
                                <p class="text">{{ post.body| truncatechars:200}}</p>
                                <a class="features-btn" href="{% url 'blog:post' post.pk %}">LEARN MORE</a>
                            </div>
                        </div> <!-- single features -->
                    </div>
                    {% endfor %}

                </div> <!-- row -->
            </div> <!-- container -->
        </section>



        <div class="container">
        {% if first_name or last_name %}
            <div class="jumbotron">
                <h1>{{ first_name }} {{ last_name }} - Blog</h1>
            </div>
        {% endif %}
    </div>
{% endblock content %}

blog/templates/blog/login.html
{% extends "blog/base.html" %}

{% block content %}
<header class="header">
        
    <div class="col-xs-12 col-sm-8 col-md-6 col-sm-offset-2 mt-10 col-md-offset-3">

        <!-- Errors messages -->
        <div class="col-sm-9">

            {% if form.errors %}
                <div class="alert alert-danger">Your username and password didn't match. Please try again.</div>
            {% else %}
                {% if next %}
                    {% if user.is_authenticated %}
                        <div class="alert alert-info">Your account doesn't have access to this page. To proceed,
                            please login with an account that has access.
                        </div>
                    {% else %}
                        <div class="alert alert-info">Please login to see this page.</div>
                    {% endif %}
                {% endif %}
            {% endif %}

        </div>
    </div>
    <div class="hero">
        <form method="post" action="{% url 'login' %}" >
            {% csrf_token %}
            <div class="hero__login form-group">
                <h1 class="heading__primary u-margin-bottom-med">Login</h1>
                <div class="u-margin-bottom-med">
                    <div class="input__label ">Username</div>
                    <input type="text" name="username" id="email" class="input__field" placeholder="aijax">
                </div>
                <div class="u-margin-bottom-med">
                        <div class="input__label ">password</div>
                        <input type="password" name="password" id="password" class="input__field" placeholder="dds12345">
                </div>
                <div class="btn__container u-margin-bottom-med">
                    <input type = "submit" class="btn btn-blue" value="Login"> login <i class="material-icons md-5">arrow_right</i></a>
                </div>
            </div>
            <input type="hidden" name="next" value="{% url 'blog:home' %}"/>

        </form>


        <div class="hero__content">
            <div class="heading__large">Welcome to<br/>
                <span class="heading__large heading__bold">Reflections,</span>
            </div>
            
            <h2 class="heading__secondary">
                Share your knowledge and opinions to the world, even if you think nobody cares.
            </h2>
        </div>

        
    </div>

</header>
{% endblock %}
  

blog/templates/blog/post.html
{% extends "blog/base.html" %} {% block content %}
<div class="container features-area ">
    <!-- Post -->
    <div class="col-sm-12" >
        <div class="single-features">
            <div class="features-title-icon d-flex justify-content-between">
                <h2 class="features-title">{{ post.title }}</h2>
            </div>

            <div class="text black">
                <i>Published on {{ post.pub_date }} by
                    <b><a href="{% url 'blog:user_posts' post.user.username %}">{{ post.user.username }}</a></b>
                </i>
            </div>

            <div class="features-content">
                <p class="text">{{ post.body }}</p>
            </div>

            <!-- Show Update and Delete button only if User is the owner of the Post -->
            {% if post.user == user %}
            <div class="row mt-20">
                <!-- Delete button -->
                <a href="{% url 'blog:delete_post' post.pk %}" class="col-md-2 pull-right">
                    <button type="button" class="btn btn-primary btn-block">
                        Delete
                    </button>
                </a>

                <!-- Update button -->
                <a href="{% url 'blog:update_post' post.pk %}" class="col-md-2 pull-right">
                    <button type="button" class="btn btn-primary btn-block">
                        Update
                    </button>
                </a>
            </div>
            {% endif %}
        </div>
    </div>
    <div class="container mt-30">
        <h4 class="">Comments:</h4>

        <!-- Show Comment button only if User is authenticated -->
        {% if user.is_authenticated %}

        <!-- Comment button -->
        <a href="{% url 'blog:create_comment' post.pk %}" class="col-md-2 pull-right mt-20">
            <button type="button" class="btn btn-primary btn-block">Comment</button>
        </a>

        {% endif %}
        <div class="row ml-20"></div>
        {% for comment in comments %}
        <div class="single-features col-sm-10 mt-10">
            <div class="features-content">
                <div class="black">
                    <i>
                        Created {{ comment.pub_date }} by
                        <b><a href="{% url 'blog:user_posts' comment.user.username %}">{{ comment.user.username }}</a></b></i>
                </div>

                <!-- Comment body -->
                <p class="text">{{ comment.body }}</p>
            </div>
        </div>
        {% endfor %}
    </div>
</div>
{% endblock content %}

blog/templates/blog/search_post.html
{% extends "blog/base.html" %}

{% block content %}

    <div class="container  " style="height: 60vh;">
        <div class="row justify-content-center ">
            <div class="col-md-6 col-md-offset-3">
                <form action="{% url 'blog:user_posts' user.username %}#blogs" method="" class="form-horizontal">
                    {% csrf_token %}
                    <!-- <div class="form-group">
                        <div class="col-sm-9">
                            <input type="text"
                                   placeholder="Search your tag here"
                                   class="form-control"
                                   name="tag"
                                   value="{{ form.title.value|default:"" }}">

                        </div>
                    </div> -->
                    <!-- <form action="" method="post">
                        {% csrf_token %} -->
                    <div class="form-group">
                        <h3>Select the tag you want to filter</h3>
                        <div class="col-sm-9 select mt-20">
                        <!-- <label for="pet-select">Select a Tag:</label> -->

                        <select name="pets" id="pet-select">
                            <option value="">Please choose an option </option>
                            <option value="tag1">tag1</option>
                            <option value="tag1">tag2</option>
                        </select>
                            <!-- <select >
                            <option selected="selected" disabled>Select Tag:</option>
                            
                            </select> -->
                        </div>
                    </div>
                        <!-- <input type="submit" value="Select">
                      </form> -->
                    <div class="form-group">
                        <div class="col-sm-5 mt-5">
                            <input type="submit" class="btn btn-primary btn-block solid"></input>

                        </div>
                    </div>

                </form>

            </div>
        </div>
    </div>
{% endblock content %}